### ISSUE TITLE
Clarify Documentation on Recording Deletion

### ISSUE THREAD

**Issue by marknoble** [Silicondust/documentation#1]
The format to delete a show is unclear on this page:

https://github.com/Silicondust/documentation/wiki/Deleting-Recordings

I was able to identify the CmdURL of a recording I wanted to delete: "CmdURL":"http://{address of servio}/recorded/cmd?id=8c1058e7"

When I sent that command above, I got an Error 400 Bad Request response.

**Comment by nickkelsey** [comment]
You need to use a HTTP POST operation rather than HTTP GET. Documentation has been updated - thanks for point it out.
